name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, prod-kediri-sehat-app]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy
      run: deploy-kediri-sehat-app